[tool:pytest]
testpaths = .
python_files = tests.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore:The `name` is not the first parameter anymore:DeprecationWarning:starlette.templating
